### PR TITLE
added a logo image. html: added comments, header image, footer and re…

### PR DESCRIPTION
**Pull request by russkinori**
…factored. css: changed order to match html elements and added comments. js: added comments and function to clear history on page reload

### CODE REVIEW

**Review by AndrewOWStyles — APPROVED** [review]
looks like the } stopping some code got removed. im at work so can't resolve any conflicts so i'll leave that up to you russ. one thing with the clear history on page reload, is that needed as it technically defeats the purpose of the local storage we've put in

**Comment by russkinori** [comment]
> looks like the } stopping some code got removed. im at work so can't resolve any conflicts so i'll leave that up to you russ. one thing with the clear history on page reload, is that needed as it technically defeats the purpose of the local storage we've put in?

The local storage allows the current user to maintain a history, so it will remain on the page as long as they continue to search and reuse the buttons. However, when a new user comes in (represented by a page refresh), they get to start from scratch without the history of the previous user.

**Comment by AndrewOWStyles** [comment]
> > looks like the } stopping some code got removed. im at work so can't resolve any conflicts so i'll leave that up to you russ. one thing with the clear history on page reload, is that needed as it technically defeats the purpose of the local storage we've put in?
> 
> The local storage allows the current user to maintain a history, so it will remain on the page as long as they continue to search and reuse the buttons. However, when a new user comes in (represented by a page refresh), they get to start from scratch without the history of the previous user.

that makes sense but if we refresh the page and no buttons are showing we have no proof of local storage working unless we open the console and show them, could we put the history clear on a clear button instead and demonstrate it that way?

**Comment by russkinori** [comment]
> > > looks like the } stopping some code got removed. im at work so can't resolve any conflicts so i'll leave that up to you russ. one thing with the clear history on page reload, is that needed as it technically defeats the purpose of the local storage we've put in?
> > 
> > 
> > The local storage allows the current user to maintain a history, so it will remain on the page as long as they continue to search and reuse the buttons. However, when a new user comes in (represented by a page refresh), they get to start from scratch without the history of the previous user.
> 
> that makes sense but if we refresh the page and no buttons are showing we have no proof of local storage working unless we open the console and show them, could we put the history clear on a clear button instead and demonstrate it that way?

Well, the console method is basically how you prove that you're using local storage. Other than that, you've also got the proof from clicking the history buttons which relaunches the search. However, I will put it on a click-button function. Do you want to merge these changes first and I'll pull and resolve?

**Comment by AndrewOWStyles** [comment]
> > > > looks like the } stopping some code got removed. im at work so can't resolve any conflicts so i'll leave that up to you russ. one thing with the clear history on page reload, is that needed as it technically defeats the purpose of the local storage we've put in?
> > > 
> > > 
> > > The local storage allows the current user to maintain a history, so it will remain on the page as long as they continue to search and reuse the buttons. However, when a new user comes in (represented by a page refresh), they get to start from scratch without the history of the previous user.
> > 
> > 
> > that makes sense but if we refresh the page and no buttons are showing we have no proof of local storage working unless we open the console and show them, could we put the history clear on a clear button instead and demonstrate it that way?
> 
> Well, the console method is basically how you prove that you're using local storage. Other than that, you've also got the proof from clicking the history buttons which relaunches the search. However, I will put it on a click-button function. Do you want to merge these changes first and I'll pull and resolve?

i'll merge the request!

**Pull request merged**
